### ISSUE TITLE
docs: how to persist data when using docker-compose.yml

### ISSUE THREAD

**Issue by devvyn** [onmomo/fluentd-gelf-docker#1]
I noticed you used proper instruction for running the containers separately, but the instructions for using `docker-compose up -d` assume additional parameters not in the `docker-compose.yml` file from this repo and not in your recommended instructions for using `docker-compose.yml`.

It looks like the example `docker run` command for the `graylog2` uses information from Graylog2's [Docker instructions](http://docs.graylog.org/en/latest/pages/installation/docker.html#persist-data). So, for consistency, to get the `docker-compose up` method to work the same way, I added a `docker-compose.override.yml` in my deployment with the following contents:

``` yaml

---
graylog2:
  environment:
    GRAYLOG_NODE_ID: dev-laptop-graylog2-0
    GRAYLOG_SERVER_SECRET: Gr4yL4p7Zy70x6P&^97494459230
  volumes:
    - ./graylog2/data:/var/opt/graylog/data
    - ./graylog2/log:/var/log/graylog
```

I just wanted to suggest at least mentioning the data persistence issue in the context of the `docker-compose` instructions, so inexperienced users of the Graylog2 image don't mistakenly believe your project has a broken Graylog2 image (when in fact the same issue exists with the [`Graylog2/allinone`](https://hub.docker.com/r/graylog2/allinone/) image from the Docker Hub).
